export const ALL_INSTITUTE_REQUEST = "ALL_INSTITUTE_REQUEST";
export const ALL_INSTITUTE_SUCCESS = "ALL_INSTITUTE_SUCCESS";
export const ALL_INSTITUTE_FAIL = "ALL_INSTITUTE_FAIL";

// update institute
export const INSTITUTE_UPDATE_REQUEST = "INSTITUTE_UPDATE_REQUEST";
export const INSTITUTE_UPDATE_SUCCESS = "INSTITUTE_UPDATE_SUCCESS";
export const INSTITUTE_UPDATE_FAIL = "INSTITUTE_UPDATE_FAIL";
export const INSTITUTE_UPDATE_RESET = "INSTITUTE_UPDATE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
