export const ALL_INSTITUTE_REQUEST = "ALL_INSTITUTE_REQUEST";
export const ALL_INSTITUTE_SUCCESS = "ALL_INSTITUTE_SUCCESS";
export const ALL_INSTITUTE_FAIL = "ALL_INSTITUTE_FAIL";

// update institute
export const INSTITUTE_UPDATE_REQUEST = "INSTITUTE_UPDATE_REQUEST";
export const INSTITUTE_UPDATE_SUCCESS = "INSTITUTE_UPDATE_SUCCESS";
export const INSTITUTE_UPDATE_FAIL = "INSTITUTE_UPDATE_FAIL";
export const INSTITUTE_UPDATE_RESET = "INSTITUTE_UPDATE_RESET";

// update institute data
export const INSTITUTE_DATA_UPDATE_REQUEST = "INSTITUTE_DATA_UPDATE_REQUEST";
export const INSTITUTE_DATA_UPDATE_SUCCESS = "INSTITUTE_DATA_UPDATE_SUCCESS";
export const INSTITUTE_DATA_UPDATE_FAIL = "INSTITUTE_DATA_UPDATE_FAIL";
export const INSTITUTE_DATA_UPDATE_RESET = "INSTITUTE_DATA_UPDATE_RESET";

// get institute details
export const INSTITUTE_DETAILS_REQUEST = "INSTITUTE_DETAILS_REQUEST";
export const INSTITUTE_DETAILS_SUCCESS = "INSTITUTE_DETAILS_SUCCESS";
export const INSTITUTE_DETAILS_FAIL = "INSTITUTE_DETAILS_FAIL";

// add new location on edit institute page
export const ADD_NEW_LOCATION = "ADD_NEW_LOCATION";

// add new faculty on edit institute page
export const ADD_NEW_FACULTY = "ADD_NEW_FACULTY";

// add new achievement on edit institute page
export const ADD_NEW_ACHIEVEMENT = "ADD_NEW_ACHIEVEMENT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
